name: reflection_app
description: チャット形式で日々の振り返りを行うためのiOSアプリ

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2

  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: false
  ios: true
  image_path: "lib/assets/icon.png"

flutter:
  uses-material-design: true
